# Generated by Django 2.2.5 on 2019-10-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nome da equipe')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('dev_team', models.ManyToManyField(to='accounts.Jogador', verbose_name='Dev Team')),
                ('product_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jogador_product_owner', to='accounts.Jogador', verbose_name='Product Owner')),
                ('scrum_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jogador_scrum_master', to='accounts.Jogador', verbose_name='Scrum Master')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
    ]
