# Generated by Django 2.2.5 on 2019-11-21 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('min_points', models.IntegerField(verbose_name='Pontos mínimos')),
                ('max_points', models.IntegerField(blank=True, null=True, verbose_name='Pontos máximos')),
                ('related_choice', models.IntegerField(blank=True, choices=[(0, 'INICIANTE'), (1, 'INTERMEDIÁRIO'), (2, 'AVANÇADO'), (3, 'MESTRE'), (4, 'JEDI')], default=0, null=True, verbose_name='Classe choice relacionada')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da equipe')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('classe', models.IntegerField(blank=True, choices=[(0, 'INICIANTE'), (1, 'INTERMEDIÁRIO'), (2, 'AVANÇADO'), (3, 'MESTRE'), (4, 'JEDI')], default=0, null=True, verbose_name='Classe do jogador')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'COMUM'), (1, 'SCRUM MASTER'), (2, 'PRODUCT OWNER')], default=0, null=True, verbose_name='Tipo de jogador')),
                ('points', models.IntegerField(default=0, verbose_name='Scrum points')),
                ('avatar', models.FileField(blank=True, default='profile_pics/default.png', help_text='apenas imagens são aceitas', null=True, upload_to='profile_pics', verbose_name='Imagem do perfil')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('init_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('level', models.IntegerField(choices=[(0, 'BAIXO'), (1, 'MÉDIO'), (2, 'ALTO')], default=0, verbose_name='Nível de dificuldade')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='Pontos')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('open', models.BooleanField(default=True, verbose_name='Concluida')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Equipe', verbose_name='Equipe')),
                ('responsaveis', models.ManyToManyField(blank=True, to='core.Jogador', verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lider', to='core.Jogador', verbose_name='Lider da equipe'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team', to='core.Jogador', verbose_name='Time'),
        ),
    ]
