# Generated by Django 2.2.5 on 2019-11-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='core.Jogador', verbose_name='Resopnsável pelo projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
