# Generated by Django 2.2.7 on 2019-11-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191105_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
            preserve_default=False,
        ),
    ]
