# Generated by Django 2.2.5 on 2019-11-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191112_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Concluida'),
        ),
    ]
