# Generated by Django 2.2.5 on 2019-11-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191118_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='project',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
