# Generated by Django 2.2.5 on 2019-11-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classe_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='jogador',
            new_name='responsaveis',
        ),
    ]
