# Generated by Django 2.2.5 on 2019-11-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191118_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Equipe', verbose_name='Equipe'),
        ),
    ]
