# Generated by Django 2.2.5 on 2019-11-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quest_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='slug',
        ),
    ]
