# Generated by Django 2.2.5 on 2019-11-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quest_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, 'BAIXO'), (1, 'MÉDIO'), (2, 'ALTO')], default=0, null=True, verbose_name='Tipo de jogador'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontos'),
        ),
    ]
