# Generated by Django 2.2.5 on 2019-11-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191119_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='level',
            field=models.IntegerField(choices=[(0, 'BAIXO'), (1, 'MÉDIO'), (2, 'ALTO')], default=0, verbose_name='Tipo de jogador'),
        ),
    ]
